apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/isaiahwong/cluster/api/gateway
    context: gateway

deploy:
  kubectl:
    manifests:
    - k8s/gateway.yaml
    - k8s/nginx-ingress/mandatory.yaml
