# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: default
---

# Role
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata: 
  namespace: default
  name: api-gateway
rules: 
- apiGroups: ["", "extensions", "apps"]
  resources: ["services", "namespaces"]
  verbs: ["get", "list"] 

--- 

# Role Binding
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: api-gateway-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-gateway
subjects:
  - kind: ServiceAccount
    name: api-gateway
    namespace: default
    
--- 

# Service
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  ports:
  - name: http
    port: 5000
    targetPort: gateway-port
  selector: 
    component: gateway
  type: ClusterIP

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: gateway
  template: 
    metadata: 
      labels: 
        component: gateway
    spec:
      serviceAccountName: api-gateway
      containers:
        - name: gateway
          image: registry.gitlab.com/isaiahwong/cluster/api/gateway
          imagePullPolicy: IfNotPresent
          ports:
            - name: gateway-port
              containerPort: 5000
          env:
          - name: NODE_ENV
            value: "development"
          - name: MAINTENANCE_MODE
            value: "false"
          - name: SVC_DISCOVERY_INTERVAL
            value: "5000"
          - name: ENABLE_CONSOLE_LOGS_IN_PROD
            value: "false"
          - name: ENABLE_CONSOLE_LOGS_IN_TEST
            value: "true"
      # imagePullSecrets:
      # - name: gitlab-auth
